[package]
name = "convert-image"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2021"
rust-version = "1.76"

[dependencies]
machine-vision-formats = { workspace = true, features = ["std"] }
image = { workspace = true, features = ["jpeg", "png"] }
thiserror.workspace = true
bayer = { version = "0.1", default-features = false }
itertools = "0.10.3"
